apiVersion: v1
kind: Secret
metadata:
  name: cloud-file-service-secret
  namespace: cloud-file-service
type: Opaque
stringData:
  DB_USERNAME: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"
  DB_URL: "jdbc:postgresql://CHANGE_ME:5432/cloud_file"