spring.application.name=backend

server.address=0.0.0.0
server.port=8080

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:${DB_URL:jdbc:postgresql://localhost:5432/cloud_file}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USERNAME:cloud_user}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:cloud_password}}
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS
aws.region=${AWS_REGION:ap-northeast-2}

# S3
aws.s3.bucket=${S3_BUCKET:local-cloud-file-service}

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB