spring:
    application:
        name: cloud-file-service

cloud:
  aws:
    region: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET:local-cloud-file-service}

server:
    port: 8080