spring.application.name=backend

server.address=0.0.0.0
server.port=8080

# AWS
aws.region=${AWS_REGION:ap-northeast-2}

# S3
aws.s3.bucket=${S3_BUCKET:local-cloud-file-service}

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB